steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/upbeat-aura-419104/gke-image/flask-image' ]
  id: 'Push Docker Image2'



    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1-c
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1-c
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1-c --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
